language: node_js
before_install:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - git remote set-url origin "https://${GH_TOKEN}@github.com/react-core/react-core.git"
script:
  - npm run lint
  - npm run test
after_success:
  - echo "TRAVIS_BRANCH= " $TRAVIS_BRANCH
  - echo "TRAVIS_PULL_REQUEST_BRANCH= " $TRAVIS_PULL_REQUEST_BRANCH
  - echo "TRAVIS_EVENT_TYPE= " $TRAVIS_EVENT_TYPE
  - echo "TRAVIS_TAG= " $TRAVIS_TAG
  - '[[ $TRAVIS_BRANCH = "master" && $TRAVIS_PULL_REQUEST_BRANCH = "" && $TRAVIS_TAG = "" ]] && make publish'
