[build]
  publish = "storybook-static"

[context.production]
  command = "npm run build:production"

[context.deploy-preview]
  command = "npm run build-storybook"

[context.testing]
  command = "npm run build-storybook"

[context.branch-deploy]
  command = "npm run build-storybook"
